sudo: false
language: python
python:
  - 3.5
cache:
  directories:
    - $HOME/.cache/pip
env:
  matrix:
    - TOXENV=py35
    - TOXENV=flake8
    - TOXENV=docs
  global:
    - PYTHONASYNCIODEBUG=1
    - PYTHONWARNINGS=default,ignore::PendingDeprecationWarning
matrix:
  fast_finish: true
install:
  - pip install 'tox>=2.3.1'
script: tox
notifications:
  on_success: never
  on_failure: change
