language: python
sudo: false
python:
- 3.4
install:
  - travis_retry pip install -e .[test]
cache:
  directories:
    - $HOME/.cache/pip
script:
  - py.test tests --cov=ncplib --cov-report=term-missing
notifications:
  on_success: never
  on_failure: change
