language: python
sudo: false
python:
- 3.4
install:
  - travis_retry pip install -e .[dev]
cache:
  directories:
    - $HOME/.cache/pip
script:
  - nosetests --cover-package=ncplib --with-coverage
notifications:
  on_success: never
  on_failure: change
