dist: trusty
language: python
python:
- 3.5
sudo: false
before_install:
- rm -rf ~/.pyenv
- curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash
- cat .python-version | xargs -n 1 pyenv install
install:
- pip install 'tox>=2.3.1'
script: tox
deploy:
  provider: pypi
  user: etianen
  password:
    secure: HUnEz+LFkETu4nci6c+RXdCE/JMrYUtO8cE1zxdgM7OauBRqvphLDIWxTmibkwJxGoAY+75rBRJLdUcUOyZhTs+dtEjmpTgRzYOjOflssvN0uc+0/Smfkf3xWaFULEOEHCypM6FuK6dwlKIh2Pn9gBazcP6kjfr/pPivASEiwqgfC0Dw5ArfU9y5C05UQhsehD/C9N9RjgOBJ6lBvXnyZ+/BdJ3bXhGtWMGQQMl7KpT+Nsmz/H5vLuaJgaUq7HYz2RQXhULNTlxb87NqZyC0s2gVRG5OtWP5OfKIuQ70HSmAYtFcZGOJ6h7oieJ4NkgmqhUWaxF5Nwqmsru8Z66fMjFp1nNPqNrFDT/1uOlFezuky7NUfuQfC8Sp1hXkB4hIaDzaefuL3WjaCX4PXHR+0HPDvYX/ZQfShU9X4S3L2hjFOg6xZbva15+CxgMPkxYQ8f9gmI0Wg7TrWY1mm+2qelspMWOolDKUUUJpMEi94LDXFINaRgBV7ofNPmJqMXMEvll1uhT7e3KdXo3HDSmQolPeXDMDjcpV6XFkGXy1zyFaLEPlwN3vlbmTOJpa3InGSq0u7NFMETzxED8/ky/ASgtWgkGEYwl3wWK9LLbdgiwk0oEsDCyWojUuZaiQNPqOoeJDFBDRDkR1TaprkeDteHWQd3tY5q2si94Grnz7raw=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: CRFS/python3-ncplib
notifications:
  on_success: never
  on_failure: change
