package:
  name: ncplib
  version: {{ environ["PACKAGE_VERSION"] }}
requirements:
  build:
    - python
    - pip
  run:
    - python
build:
  script: pip install .
test:
  commands:
    - pip install '{{ environ["SRC_DIR"] }}[dev]'
    - python -m unittest discover ncplib.tests
    - coverage report
    - flake8 {{ environ["SRC_DIR"] }}/ncplib
about:
  home: https://github.com/CRFS/python3-ncplib
  summary: "CRFS NCP library for Python 3."
